# Generated by Django 4.2.30 on 2026-04-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ai_summary',
            field=models.TextField(blank=True, help_text='Clean AI-generated product summary'),
        ),
        migrations.AddField(
            model_name='product',
            name='attributes',
            field=models.JSONField(default=dict, help_text='Strict keys: vehicle_type, usage, style, terrain, durability'),
        ),
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='bolt_pattern',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='diameter',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='embedding_text',
            field=models.TextField(blank=True, help_text="The 'Golden String' used for high-quality Vector generation"),
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.JSONField(default=list, help_text='JSON Array of key product features'),
        ),
        migrations.AddField(
            model_name='product',
            name='finish',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='offset',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='part_number',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price_category',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
    ]
