# Generated by Django 4.2.30 on 2026-04-21 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_product_ai_summary_product_attributes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSession',
            fields=[
                ('session_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('sales_stage', models.CharField(choices=[('discovery', 'Discovery'), ('fitment_validation', 'Fitment Validation'), ('ready_to_recommend', 'Ready to Recommend'), ('closing', 'Closing')], db_index=True, default='discovery', max_length=50)),
                ('vehicle_data', models.JSONField(blank=True, default=dict, help_text='Stores parsed Year, Make, Model, and specific DB-matched Type')),
                ('identified_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('identified_style', models.JSONField(blank=True, default=dict, help_text='Stores style preferences (e.g., finish, usage, off-road vs street)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='chatbot.lead')),
            ],
        ),
    ]
