# Generated by Django 4.2.30 on 2026-04-21 13:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_agentsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fitment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('make', models.CharField(db_index=True, max_length=100)),
                ('model', models.CharField(db_index=True, max_length=100)),
                ('year_from', models.IntegerField(db_index=True)),
                ('year_to', models.IntegerField(db_index=True)),
                ('bolt_pattern', models.CharField(blank=True, max_length=50, null=True)),
                ('center_bore', models.FloatField(blank=True, null=True)),
                ('offset_min', models.FloatField(blank=True, null=True)),
                ('offset_max', models.FloatField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitments', to='chatbot.product')),
            ],
            options={
                'verbose_name': 'Fitment',
                'verbose_name_plural': 'Fitments',
                'indexes': [models.Index(fields=['make', 'model'], name='chatbot_fit_make_093c20_idx')],
            },
        ),
    ]
