# Generated by Django 4.2.30 on 2026-04-28 07:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_fitment'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoltPatternRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('make', models.CharField(db_index=True, help_text='Vehicle Make (e.g. ford, honda)', max_length=100)),
                ('model', models.CharField(blank=True, db_index=True, help_text='Optional Vehicle Model (e.g. f-150)', max_length=100, null=True)),
                ('patterns', models.JSONField(help_text='List of valid bolt patterns e.g. ["5x114.3", "6x135"]')),
            ],
            options={
                'verbose_name': 'Bolt Pattern Rule',
                'verbose_name_plural': 'Bolt Pattern Rules',
            },
        ),
        migrations.CreateModel(
            name='VehicleTypeLimit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_type', models.CharField(db_index=True, help_text='e.g. sedan, suv, truck', max_length=50, unique=True)),
                ('max_diameter', models.FloatField(help_text='Maximum allowed wheel diameter in inches')),
                ('max_width', models.FloatField(help_text='Maximum allowed wheel width in inches')),
            ],
            options={
                'verbose_name': 'Vehicle Type Limit',
                'verbose_name_plural': 'Vehicle Type Limits',
            },
        ),
        migrations.AddField(
            model_name='brand',
            name='is_wheel_brand',
            field=models.BooleanField(db_index=True, default=False, help_text='Flags this brand as a known wheel manufacturer'),
        ),
        migrations.AddConstraint(
            model_name='boltpatternrule',
            constraint=models.UniqueConstraint(fields=('make', 'model'), name='unique_make_model_rule'),
        ),
    ]
