# Generated by Django 4.2.30 on 2026-05-04 07:56

from django.db import migrations, models
import pgvector.django.indexes
import pgvector.django.vector
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_boltpatternrule_vehicletypelimit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleMake',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('make_fitment_id', models.CharField(db_index=True, max_length=100)),
                ('year', models.IntegerField(db_index=True)),
                ('model_fitment_id', models.CharField(db_index=True, max_length=100)),
                ('model_fitment_value', models.CharField(db_index=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Vehicle Make',
                'verbose_name_plural': 'Vehicle Makes',
            },
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('make_fitment_id', models.CharField(db_index=True, max_length=100)),
                ('year', models.IntegerField(db_index=True)),
                ('model_fitment_id', models.CharField(db_index=True, max_length=100)),
                ('model_fitment_value', models.CharField(db_index=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Vehicle Model',
                'verbose_name_plural': 'Vehicle Models',
            },
        ),
        migrations.CreateModel(
            name='VehicleYear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField(db_index=True, unique=True)),
            ],
            options={
                'verbose_name': 'Vehicle Year',
                'verbose_name_plural': 'Vehicle Years',
            },
        ),
        migrations.CreateModel(
            name='WheelProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(db_index=True, max_length=100, unique=True)),
                ('product_name', models.CharField(db_index=True, max_length=255)),
                ('product_desc', models.TextField(blank=True, null=True)),
                ('brand_desc', models.CharField(db_index=True, max_length=100)),
                ('style', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('fancy_finish_desc', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('diameter', models.FloatField(blank=True, db_index=True, null=True)),
                ('width', models.FloatField(blank=True, db_index=True, null=True)),
                ('bolt_pattern_metric', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('bolt_pattern_standard', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('wheel_offset', models.CharField(blank=True, max_length=50, null=True)),
                ('backspacing', models.FloatField(blank=True, null=True)),
                ('centerbore', models.FloatField(blank=True, null=True)),
                ('image_url1', models.URLField(blank=True, max_length=1000, null=True)),
                ('category_name', models.CharField(blank=True, max_length=100, null=True)),
                ('size_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('map_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('embedding_text', models.TextField(blank=True, help_text="The 'Golden String' used for high-quality Vector generation")),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
            ],
            options={
                'verbose_name': 'Wheel Product',
                'verbose_name_plural': 'Wheel Products',
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='wheel_prod_embedding_idx', opclasses=['vector_cosine_ops'])],
            },
        ),
    ]
