# Generated by Django 4.2.30 on 2026-05-04 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_vehiclemake_vehiclemodel_vehicleyear_wheelproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BoltPatternRule',
        ),
        migrations.RemoveField(
            model_name='fitment',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='VehicleTypeLimit',
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='chatbot.wheelproduct'),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Fitment',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
