# Generated by Django 4.2.30 on 2026-05-04 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0008_delete_boltpatternrule_remove_fitment_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiclemake',
            old_name='model_fitment_value',
            new_name='make_fitment_value',
        ),
        migrations.RenameField(
            model_name='vehiclemake',
            old_name='year',
            new_name='years',
        ),
        migrations.RemoveField(
            model_name='vehiclemake',
            name='model_fitment_id',
        ),
    ]
